//! Jekyll 文档渲染器模块
//!
//! 负责将解析后的文档渲染为 HTML

use super::parser::ParsedDocument;
use crate::{
    jekyll::{JekyllConfig, MarkdownConverter},
    types::Result,
};

/// Jekyll 文档渲染器
pub struct JekyllRenderer {
    /// Markdown 转换器
    markdown_converter: MarkdownConverter,
}

impl JekyllRenderer {
    /// 创建新的渲染器
    pub fn new() -> Self {
        Self { markdown_converter: MarkdownConverter::new() }
    }

    /// 渲染文档
    ///
    /// # Arguments
    ///
    /// * `document` - 解析后的文档
    /// * `config` - Jekyll 配置
    ///
    /// # Returns
    ///
    /// 渲染后的 HTML
    pub fn render(&self, document: &ParsedDocument, config: &JekyllConfig) -> Result<String> {
        // 转换 Markdown 为 HTML
        let html_content = self.markdown_converter.convert(&document.content)?;

        // 构建完整的 HTML 页面
        let html = self.build_html_page(document, &html_content, config);

        Ok(html)
    }

    /// 构建完整的 HTML 页面
    fn build_html_page(&self, document: &ParsedDocument, content: &str, config: &JekyllConfig) -> String {
        let title = document.title.as_deref().unwrap_or("Untitled");
        let site_title = config.title.as_deref().unwrap_or("Jekyll Site");

        format!(
            r#"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} | {site_title}</title>
</head>
<body>
    <header>
        <h1>{site_title}</h1>
    </header>
    <main>
        <article>
            <h2>{title}</h2>
            {content}
        </article>
    </main>
    <footer>
        <p>Generated by Jekyll</p>
    </footer>
</body>
</html>
"#
        )
    }
}

impl Default for JekyllRenderer {
    fn default() -> Self {
        Self::new()
    }
}
